### ISSUE TITLE
Libra GOB XSIAM Agent install

### ISSUE THREAD

**Issue by Alkadhimi** [hmcts/roadmap-platform-operations#2176]
https://tools.hmcts.net/jira/browse/DTSPO-18565

**Comment by danielwilsonkainos** [comment]
LibraGOB application is hosted as AKS service. There were some DB migration VMs in the past used to migrate from Oracle to Azure hosted Postgresql Flexible but these are now decommissioned and only the recovery point remains in case its needed.

This leaves nothing in LibraGOB which requires an agent installation so this work can be withdrawn. Have confirmed with Richard R
