### ISSUE TITLE
FACT - Update HTTP Security headers

### ISSUE THREAD

**Issue by naconnolly** [hmcts/roadmap-platform-operations#2266]
DTSPO-19466

**Comment by naconnolly** [comment]
https://tools.hmcts.net/jira/browse/DTSPO-19466

**Comment by reespozzi** [comment]
This will be handled by FACT team: https://tools.hmcts.net/jira/browse/FACT-2046 -- we are focussed on front door enablement for caching and compression. Will keep this open in parallel and close both off
