### ISSUE TITLE
CTSC Reporting Service - Part3 (120)

### ISSUE THREAD

**Issue by timja** [hmcts/roadmap-platform-operations#436]
<div><a href="https://tools.hmcts.net/jira/browse/DTSPO-12407">https://tools.hmcts.net/jira/browse/DTSPO-12407</a><span style="display:inline !important;">&nbsp;- Can be scheduled in Sprint 61 as already working on it</span><br> </div><div> </div><div><a href="https://tools.hmcts.net/jira/browse/DTSPO-13026">https://tools.hmcts.net/jira/browse/DTSPO-13026</a>&nbsp;- Can be scheduled in Sprint 63 in the hope that the business would be ready for production this time<br> </div><div><br> </div><div>Felix has indicated that CTSC are not yet ready for this, provisionally ready in S66 </div><div> </div>

**Comment by madjava** [comment]
Prod data gateway has been setup and waiting for CTSC go live, no more for us to do as per this epic
