### ISSUE TITLE
Explore effort & cost associated with Elastic Cloud (157)

### ISSUE THREAD

**Issue by timja** [hmcts/roadmap-platform-operations#456]
DTSPO-2473

## Summary

The VMs running ElasticSearch for both CCD and Camunda are on old versions of Ubuntu. These are now being flagged as a risk to the organisation. We therefore need to work out if we can migrate to Elastic cloud, or continue running IaaS and upgrade Ubuntu.

## Intended Outcome

We know the feasibility, effort and cost of moving to Elastic Cloud to inform an HLD / Presentation at TAB on a decision. Tim has a bunch of notes and investigation completed (see comments), so please speak to him to start. `Rich` Tim and Thomas to create HLD template we can use (similar to recent App proxy and VPN).

We should try to investigate each of the categories needed to complete the HLD (template link here: https://tools.hmcts.net/confluence/x/6YUSZg )

**Comment by madjava** [comment]
Epic: https://tools.hmcts.net/jira/browse/DTSPO-15917
