### ISSUE TITLE
Auto-shutdown phase 3 (147)

### ISSUE THREAD

**Issue by timja** [hmcts/roadmap-platform-operations#471]
DTSPO-13521

## Summary

*Add a summary of the requirement here*

## Intended Outcome

*What is the outcome going to be*

## Impact on Teams

*How will this impact teams, put 'No impact' if none*

**Comment by madjava** [comment]
Epic link here: https://tools.hmcts.net/jira/browse/DTSPO-14610

**Comment by timja** [comment]
@madjava there's already an epic here?
https://tools.hmcts.net/jira/browse/DTSPO-13520
