### ISSUE TITLE
Camunda Review

### ISSUE THREAD

**Issue by naconnolly** [hmcts/roadmap-platform-operations#706]

**Comment by madjava** [comment]
Link to Epic: https://tools.hmcts.net/jira/browse/DTSPO-17624

**Comment by reespozzi** [comment]
This was a manual issue created to track work being done - this epic : https://tools.hmcts.net/jira/browse/DTSPO-17624 is in relation to the requirement https://tools.hmcts.net/jira/browse/DTSPO-17553 coming up in red. Marty has done a first pass through all documentation to be reviewed / added to as appropriate during the historical cleanup work
